### ISSUE TITLE
Make shortcut command for generating translations

### ISSUE THREAD

**Issue by rubickcz** [druids/developers-chamber#17]
Currently, to generate translations, the command must be issued by hand with flags `pydev run-dj makemessages -l=cs --no-location`. It would be nice if a shorcut command would exist, like `pydev makemessages`. It would be a nice counterpart to `pydev makemigrations` imho.

**Comment by matllubos** [comment]
Yes It will be simple with alias. We will add it to the projects.

**Comment by matllubos** [comment]
It is little bit complicated, because you need all python files for localization :(
