### ISSUE TITLE
Improve handling of CTRL+C termination

### ISSUE THREAD

**Issue by radimsuckr** [druids/developers-chamber#21]
For example, when running Docker Compose, CTRL+C should forward directly to Docker Compose, i.e. first press should initiate soft shutdown and second should do hard shutdown etc..

**Comment by rubickcz** [comment]
What is it doing right now, when you press Ctrl+C

**Comment by matllubos** [comment]
kill the subprocess and parent we need do something like this
try
    a = subprocess.Popen(['command'])
except KeyboardInterrupt:
    os.kill(a.pid, signal.SIGTERM)
a.wait to complete
